<?php
// routes/jadwal_harian.php

return [
    1 => ['Matematika', 'Duolingo'],
    2 => ['Bahasa Indonesia', 'Biologi', 'Duolingo'],
    3 => ['Bahasa Inggris', 'Fisika', 'Duolingo'],
    4 => ['Matematika', 'Biologi', 'Duolingo'],
    5 => ['Bahasa Inggris', 'Bahasa Indonesia', 'Duolingo'],
    6 => ['Fisika', 'Duolingo'],
    7 => ['Review Materi SMP (YouTube)', 'Duolingo'],
    8 => ['Bahasa Indonesia', 'Matematika', 'Duolingo'],
    9 => ['Fisika', 'Biologi', 'Duolingo'],
    10 => ['Bahasa Inggris', 'Duolingo'],
    11 => ['Review Biologi Kelas 10', 'Duolingo'],
    12 => ['Matematika', 'Fisika', 'Duolingo'],
    13 => ['Bahasa Indonesia', 'Duolingo'],
    14 => ['Bahasa Inggris', 'Matematika', 'Duolingo'],
    15 => ['Biologi', 'Duolingo'],
    16 => ['Bahasa Indonesia', 'Fisika', 'Duolingo'],
    17 => ['Latihan Soal Matematika', 'Duolingo'],
    18 => ['Latihan Soal Bahasa Inggris', 'Duolingo'],
    19 => ['Review Materi Fisika', 'Duolingo'],
    20 => ['Bahasa Indonesia', 'Biologi', 'Duolingo'],
    21 => ['Matematika', 'Duolingo'],
    22 => ['Bahasa Inggris', 'Fisika', 'Duolingo'],
    23 => ['Latihan Soal Biologi', 'Duolingo'],
    24 => ['Bahasa Indonesia', 'Duolingo'],
    25 => ['Matematika', 'Biologi', 'Duolingo'],
    26 => ['Review Materi Bahasa Inggris', 'Duolingo'],
    27 => ['Fisika', 'Bahasa Indonesia', 'Duolingo'],
    28 => ['Latihan Soal Campuran', 'Duolingo'],
    29 => ['Bahasa Inggris', 'Matematika', 'Duolingo'],
    30 => ['Refleksi Akhir & Review Umum', 'Duolingo'],
];
